### PR TITLE
Login style

### PR DESCRIPTION
**Pull request by nogainbar**
Implemented styles to login page according to designs. 

I used the hierarchy and numeric values of Tachyon so currently does not follow designs in pixels values as in designs, but is a good start. :)

### CODE REVIEW

**Comment by nogainbar** [comment]
Also added the free goole font 'Didact Gothic' for now until adding the original font with @fontface

**Comment by nogainbar** [comment]
Fixes #192

**Comment by MollieCourtenay** [comment]
Am I meant to be assigned to this issue?

**Comment by katbow** [comment]
Nope, I'll remove the assignment now.

**Pull request merged**
