### PR TITLE
Refactor caseload

### PR DESCRIPTION
**Pull request by tonydaly**
Refactor of the caseload routes, to prepare for the service user messaging. Moves most of the existing controllers into the `Caseload` namespace.

Now the routes look like:
```
                   caseload_path  GET     /caseload                                   Healthlocker.CaseloadController :index
              caseload_user_path  GET     /caseload/users/:id                         Healthlocker.Caseload.UserController :show
         caseload_user_room_path  GET     /caseload/users/:user_id/rooms/:id          Healthlocker.Caseload.RoomController :show
```

Where previously the routes (and controllers) were using a `caseload_id` which was not really a domain object of ours. This should make the routes clearer and make extending the caseload area easier.

Also, renames the `MessageController` to `RoomController` as this is more reflective of it's responsibilities.

### CODE REVIEW

**Comment by katbow** [comment]
The only issue I'm noticing is when I'm logged in as a clinician -> go to carer so I see messages & another tab for contacts -> click contacts and I get this

image

**Comment by tonydaly** [comment]
@nelsonic actually it's many-to-many a User can have many Rooms and a Room can have many Users.

`/caseload/users/5/rooms/1` 
`/caseload/users/5/rooms/2` 

Same user, but could view the resource for different Rooms.

However currently, there's only really one Room each atm.

**Comment by tonydaly** [comment]
@katbow that's actually an existing issue so will be fixed separately.

**Comment by katbow** [comment]
@tonydaly ahh gotcha. Sounds good 👍

**Pull request merged**
