### PR TITLE
[WIP] adding linting and code coverage to travis build

### LINKED ISSUE #396: Linter?
What are your thoughts on setting up a linter?
[dogma](https://github.com/lpil/dogma) seems good (took about 2 mins to get set up) (may take longer to fix the linting errors).
I ran it in the project and there are a couple of long lines and inconsistencies (pretty good though)

### PR DESCRIPTION
**Pull request by shouston3**
Fixes #396 
- [x] Set up linter
- [x] Set up codecov
- [ ] Fix linting issues

### CODE REVIEW

**Comment by shouston3** [comment]
@tonydaly is this a good way to go about #396 (just before we go about addressing all of the linting issues)

**Comment by tonydaly** [comment]
@shouston3 looks good! Before addressing the issues we should agree on the linter rules by [configuring](https://github.com/rrrene/credo#configuration-via-credoexs) our own.

I also wouldn't generally fix all of the issues in one go, but instead, fix the ones that appear in files you work on (otherwise your name will come up on everything after a git blame 😛).

**Comment by tonydaly** [comment]
Also, will this fail the build if it doesn't pass the linter? If so I'm not so sure about that, don't really want to be blocked from deploying by the linter.

**Comment by shouston3** [comment]
Readme cleanup has since been addressed here: https://github.com/healthlocker/healthlocker/commits/master/README.md

Hound has since been set up and we are now using hound over travis for picking up on code quality (linting) issues

**Pull request closed without merging**
