### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by tonydaly**
Added a new route "/components", where we can create / view our components. Got a very basic button in there, but mostly playing around with Tachyons.

## Todo

- Need to generate typography styles and other things to add to the `body`
- Build out other necessary components

Here's the dropbox links to some styles: https://www.dropbox.com/sh/oxvwi0eh6xlkj03/AABdIQSYCz4AiMNKABpWPH-4a?dl=0 I've also got a printed version. 
@indiamindwave24 are these the latests?

### CODE REVIEW

**Comment by tonydaly** [comment]
@nelsonic @katbow this is where I got to last week, it's still a WIP as most of the styling is only in the components view and hasn't been integrated with the actual templates.

**Comment by nelsonic** [comment]
@tonydaly thanks for updating. 👍

**Comment by indiamindwave24** [comment]
@tonydaly Sorry, I missed this — these are the most up to date style guides

**Comment by tonydaly** [comment]
@indiamindwave24 do you have a link to the style guide on Dropbox?

**Comment by tonydaly** [comment]
@nelsonic @katbow Be good to get your feedback on 73e93312af489d55f1d098767e5ce0677d49b33b.

I think we're going to run into a bunch of issues attempting to apply styling to Markdown content. This implementation is very naive and doesn't take into account other HTML elements e.g images.

But I'm not sure how to get around this atm? 

[earmark](https://github.com/pragdave/earmark) does have a way to [add HTML attributes](https://github.com/pragdave/earmark#adding-html-attributes-with-the-ial-extension), but this would have to be done at the content level?

Thoughts?

**Comment by tonydaly** [comment]
[Review App](https://healthlocker-pr-30.herokuapp.com/)

**Comment by tonydaly** [comment]
@nelsonic I don't have access to the latest style guide, so this is just Tachyons blue. Agreed I think it'll be better to get it in, then make smaller PRs with updates.

**Comment by nelsonic** [comment]
@katbow please give second pair of eyes on this PR.
and merge when happy.
@Cleop please sit with Kat when she is reviewing so you're up-to-date too. thanks! 👍

**Comment by katbow** [comment]
I'm not ignoring this one! @Cleop isn't in today and I didn't think it was blocking to not merge in yet. I think it would be good for us to review together when she's in tomorrow

**Comment by nelsonic** [comment]
@katbow thanks for resolving the merge conflict. 👍 
@tonydaly once again thanks for the great work on this PR. 🍦  🚀 
merging. ✅

**Pull request merged**
