### PR TITLE
WIP - Automated browser tests

### PR DESCRIPTION
**Pull request by Cleop**
Created initial automated tests for sign up flow errors (invalid email, invalid pw, existing account and empty fields) as well as a couple for clicking through (not logged in) to view stories pages.

### CODE REVIEW

**Comment by tonydaly** [comment]
@Cleop is the code in the `js` files auto-generated by the chrome plugin? Especially the CSS selectors? 

I'm a little bit concerned that if they're generated like this they'll be very brittle. Thoughts @nelsonic?

**Comment by Cleop** [comment]
@tonydaly yes this is, apart from all of the evaluate parts have to be hand written. 

You're correct in saying that it relies on CSS selectors, is this not the case with all automated browser testing?

**Comment by tonydaly** [comment]
@Cleop sorry I meant I was concerned about the _specificity_ of the selectors. 

For example using [`wallaby`](https://github.com/keathley/wallaby) you would write a selector like `Query.css(".some-css")` to find an element with that class. However, the selector being automatically generated from nightmare looks more like: 

```
'main#body > section.h-100.pa3.pa5-ns.bt.b--black-10.bg-white:nth-child(1) > section.mw7.center:nth-child(1) > section.bb.b--black-20.pb3.ph3.center:nth-child(3) > p:nth-child(4) > a:nth-child(2)'
```

The main issue with this example is that is we change any of the CSS on any of the parent elements then this selector would fail and the test wouldn't pass. This is what I meant by "brittle".

I don't know if there's a way to make them less specific, TBH I think it's the downside of an automatic tool, it has no way of knowing, so instead it has to be as specific as possible.

**Comment by Cleop** [comment]
Oh I see, I thought that that was just a reflection of the multiple nature of tachyons classes.

**Comment by iteles** [comment]
These tests were useful at the time, but the CSS has now been changed and they will need updating in future to continue to be useful 👍

**Pull request closed without merging**
