### PR TITLE
Configure hound for elixir.

### PR DESCRIPTION
**Pull request by tonydaly**
https://houndci.com/repos

### CODE REVIEW

**Comment by nelsonic** [comment]
@tonydaly we discussed this _verbally_, would you mind creating an issue so we can _capture_ the discussion/reasoning for using Hound? thanks! ❤️

**Comment by nelsonic** [comment]
@tonydaly we're happy to use _hound_ please fix merge conflicts so we get it in soon. thanks! 👍

**Comment by tonydaly** [comment]
@nelsonic rebased :)

**Comment by nelsonic** [comment]
is Elixir in "beta" on Hound CI...? (_just cause it isn't listed on the front page..._)
image

**Comment by tonydaly** [comment]
@nelsonic it's in "early testing phase": https://twitter.com/thorncp/status/827537966381703168

**Pull request merged**
